### ISSUE TITLE
Webstorm support

### ISSUE THREAD

**Issue by bluejamesbond** [babel/example-node-server#11]
Not an issue; just a recommendation (maybe).

If the sourcemaps are modified slightly, you can get Webstorm and Babel to work very well in the same folder. This way, you can potentially avoid the `/dist` folder. In fact, the Webstorm Debugger works on breakpoints on either the compiled or the es6 files. NOTE: Using find/replace (naive I know), we can make sure that all `import '*.es6'` file dependencies are changed to the `import '*.compiled.js'` files.

<img width="301" alt="screenshot 2016-02-21 23 49 22" src="https://cloud.githubusercontent.com/assets/376453/13211513/8287a4ec-d8fe-11e5-99c5-23153c2ae507.png">

**Comment by thejameskyle** [comment]
I think its just easier for people to grok compiling an entire directory into another, you would need other tools to do it the way you suggest.
