### ISSUE TITLE
Is babel-core/register production ready?

### ISSUE THREAD

**Issue by hyzhak** [babel/example-node-server#13]
Can we do that way in production without falling in performance pit trap?

``` javascript
//  enable runtime transpilation to use ES6/7 in node

/* eslint-disable */
var fs = require('fs');
var path = require('path');

var babelrc = fs.readFileSync(path.resolve(__dirname, '../.babelrc'));
var config;

try {
  config = JSON.parse(babelrc);
} catch (err) {
  console.error('==>     ERROR: Error parsing your babelrc');
  console.error(err);
}
/* eslint-enable */

require('babel-core/register')(config);
```

got example from https://github.com/bdefore/universal-redux/blob/master/bin/transpile.js

**Comment by thejameskyle** [comment]
No and it's never going to be, it's a bad idea for production because it requires recompilation at runtime, which is the whole point of the register hook.

**Comment by hyzhak** [comment]
@thejameskyle Thanks for answering. But current example https://github.com/babel/example-node-server is product ready or at least right direction for it. Right?

**Comment by thejameskyle** [comment]
Yeah https://github.com/babel/example-node-server#getting-ready-for-production-use
