### ISSUE TITLE
Script in "Watching file changes with nodemon" doesn't work

### ISSUE THREAD

**Issue by wenheqi** [babel/example-node-server#53]
Please correct me if I interpret the section "Watching file changes with nodemon" wrong.

What I found in this section is that after issue `npm start`, the project won't rebuild when index.js is modified, i.e. when I modified the greetings, it was not updated when I refresh the page. The script seems only to build the project once when the command is issued.

Following script works for me:
```
"start": "nodemon --exec \"npm run build && node dist/index.js\" -e js --ignore dist/"
```

**Comment by cunneen** [comment]
Thank you for posting this @wenheqi your solution worked for me.

**Comment by koistya** [comment]
`"start": "nodemon ./src"` + Nodemon configuration

https://github.com/kriasoft/nodejs-api-starter/blob/613b7748c3d098bc0fd2f92f3c356b32fd370313/api/package.json#L80-L83

**Comment by MacgyverMartins** [comment]
> Please correct me if I interpret the section "Watching file changes with nodemon" wrong.
> 
> What I found in this section is that after issue `npm start`, the project won't rebuild when index.js is modified, i.e. when I modified the greetings, it was not updated when I refresh the page. The script seems only to build the project once when the command is issued.
> 
> Following script works for me:
> 
> ```
> "start": "nodemon --exec \"npm run build && node dist/index.js\" -e js --ignore dist/"
> ```

Thanks!!
