### ISSUE TITLE
Code coverage with babel

### ISSUE THREAD

**Issue by jonathansamines** [babel/example-node-server#7]
It would be good to make a code coverage tool to work with babel. I have tried to configure both istanbul, babel-istanbul/isparta to get a correct code coverage report, but i haven´t be able to get the correct code references on the report. I didn´t even know if the coverage metrics are right.

Could you provide an example for this setup?
There is another coverage tool besides istanbul which plays better with babel?

Thank you!

**Comment by amcdnl** [comment]
@jonathansamines heres an example: https://gist.github.com/amcdnl/fe31562a3919914fad0e

**Comment by jonathansamines** [comment]
Thank your for that, i will give it a try. But I was wondering if was possible to do the same only with the command line tools provided by istanbul and babel. I have tried some setups to make that and I succeeded getting a coverage report, but the code shown in the report it is not the original code but the transpiled code.

**Comment by amcdnl** [comment]
@jonathansamines Ya, i stabbed at it for a while and finally gave up...just so much easier to do in code ;)

**Comment by jonathansamines** [comment]
@amcdnl Yeah, i gave up too. Btw, the gulp setup worked as a charm!

**Comment by amcdnl** [comment]
@jonathansamines w00t! 
@thejameskyle - feel free to steal my sample if you like.
